//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistantLearningSystem.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concept
    {
        public Concept()
        {
            this.Connections = new HashSet<Connection>();
            this.Connections1 = new HashSet<Connection>();
            this.Definitions = new HashSet<Definition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<int> Rating { get; set; }
        public int Status { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string ImgSrc { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual ICollection<Connection> Connections { get; set; }
        public virtual ICollection<Connection> Connections1 { get; set; }
        public virtual ICollection<Definition> Definitions { get; set; }
    }
}
