//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistantLearningSystem.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public Connection()
        {
            this.StudentConnections = new HashSet<StudentConnection>();
        }
    
        public int Id { get; set; }
        public int ClassificationId { get; set; }
        public Nullable<int> ParentConceptId { get; set; }
        public Nullable<int> ChildConceptId { get; set; }
    
        public virtual Classification Classification { get; set; }
        public virtual Concept Concept { get; set; }
        public virtual Concept Concept1 { get; set; }
        public virtual ICollection<StudentConnection> StudentConnections { get; set; }
    }
}
