//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistantLearningSystem.Models.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourseDataBaseEntities : DbContext
    {
        public CourseDataBaseEntities()
            : base("name=CourseDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classification> Classifications { get; set; }
        public virtual DbSet<ClassificationType> ClassificationTypes { get; set; }
        public virtual DbSet<Concept> Concepts { get; set; }
        public virtual DbSet<Connection> Connections { get; set; }
        public virtual DbSet<Definition> Definitions { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Formulation> Formulations { get; set; }
        public virtual DbSet<Lecturer> Lecturers { get; set; }
        public virtual DbSet<Reference> References { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentConnection> StudentConnections { get; set; }
        public virtual DbSet<StudentGroup> StudentGroups { get; set; }
    }
}
