//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistantLearningSystem.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Definition
    {
        public Definition()
        {
            this.Formulations = new HashSet<Formulation>();
            this.References = new HashSet<Reference>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<int> Rating { get; set; }
        public int Status { get; set; }
        public int ConceptId { get; set; }
        public Nullable<int> StudentId { get; set; }
    
        public virtual Concept Concept { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<Formulation> Formulations { get; set; }
        public virtual ICollection<Reference> References { get; set; }
    }
}
