//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistantLearningSystem.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Lecturers = new HashSet<Lecturer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> FacultyId { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual ICollection<Lecturer> Lecturers { get; set; }
    }
}
