//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistantLearningSystem.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public Source()
        {
            this.References = new HashSet<Reference>();
        }
    
        public int Id { get; set; }
        public string FullTitle { get; set; }
        public string Author { get; set; }
        public int Type { get; set; }
        public int PublicationYear { get; set; }
    
        public virtual ICollection<Reference> References { get; set; }
    }
}
