//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistantLearningSystem.Models.DataModels
{
    using System;
    using System.Collections.Generic;

    public partial class Student
    {
        public Student()
        {
            this.Classifications = new HashSet<Classification>();
            this.Concepts = new HashSet<Concept>();
            this.Definitions = new HashSet<Definition>();
            this.Formulations = new HashSet<Formulation>();
            this.References = new HashSet<Reference>();
            this.StudentConnections = new HashSet<StudentConnection>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int GroupId { get; set; }
        public System.DateTime RegDate { get; set; }
        public System.DateTime LastVisitDate { get; set; }
        public Nullable<int> LecturerId { get; set; }
        public string LastName { get; set; }
        public string ImgSrc { get; set; }
        public int Activation { get; set; }

        public virtual ICollection<Classification> Classifications { get; set; }
        public virtual ICollection<Concept> Concepts { get; set; }
        public virtual ICollection<Definition> Definitions { get; set; }
        public virtual ICollection<Formulation> Formulations { get; set; }
        public virtual Lecturer Lecturer { get; set; }
        public virtual ICollection<Reference> References { get; set; }
        public virtual StudentGroup StudentGroup { get; set; }
        public virtual ICollection<StudentConnection> StudentConnections { get; set; }

        public static explicit operator UserModel(Student student)
        {
            return new UserModel()
            {
                Id = student.Id,
                Login = student.Login,
                Name = student.Name,
                Password = student.Password,
                UserType = UserType.Student,
                LastName = student.LastName,
                Email = student.Email
            };
        }

    }
}
